# Generated by Django 4.2.1 on 2023-07-15 19:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("model_used", models.CharField(blank=True, max_length=700, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("text_area", ckeditor.fields.RichTextField()),
                ("job_description_url", models.URLField(blank=True, null=True)),
                ("description_text", models.TextField()),
                ("person", models.CharField(blank=True, max_length=1000, null=True)),
                ("company_name", models.CharField(max_length=1000)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("show_company_name_on_pdf", models.BooleanField(default=True)),
                ("street", models.CharField(blank=True, max_length=1000, null=True)),
                ("city", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "state_provence",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "postal_zip_code",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
        migrations.CreateModel(
            name="UserJobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=1000)),
                ("show_my_name_on_pdf", models.BooleanField(default=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("street", models.CharField(blank=True, max_length=1000, null=True)),
                ("city", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "state_provence",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "postal_zip_code",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("description", models.CharField(max_length=700)),
                ("resume_path", models.FileField(upload_to="user_resumes")),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PdfContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("llm_text", ckeditor.fields.RichTextField()),
                (
                    "cover_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covers",
                        to="resumes.coverletter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
        migrations.AddField(
            model_name="coverletter",
            name="resume_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to="resumes.resume",
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
