from django.db import models
import uuid
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Pagetext(models.Model):

    url_1 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_1 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_1")
    url_link_description_1 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_1")
    url_2 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_2 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_2")
    url_link_description_2 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_2")
    url_3 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_3 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_3")
    url_link_description_3 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_3")
    url_4 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_4 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_4")
    url_link_description_4 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_4") 
    url_5 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_5 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_5")
    url_link_description_5 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_5")
    url_6 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_6 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_6")
    url_link_description_6 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_6")
    url_7 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_7 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_7")
    url_link_description_7 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_7")
    url_8 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_8 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_8")
    url_link_description_8 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_8")
    url_9 = models.URLField(blank=True, null=True, default='https://chesnowitz.com/')
    url_link_text_9 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_text_9")
    url_link_description_9 = models.CharField(max_length=1000, blank=True, null=True, default="url_link_description_9")
    text_1 = RichTextField(blank=True, null=True, default="text_1")
    text_2 = RichTextField(blank=True, null=True, default="text_2")
    text_3 = RichTextField(blank=True, null=True, default="text_3")
    text_4 = RichTextField(blank=True, null=True, default="text_4")
    text_5 = RichTextField(blank=True, null=True, default="text_5")
    text_6 = RichTextField(blank=True, null=True, default="text_6")
    text_7 = RichTextField(blank=True, null=True, default="text_7")
    text_8 = RichTextField(blank=True, null=True, default="text_8")
    text_9 = RichTextField(blank=True, null=True, default="text_9")
    text_10 = RichTextField(blank=True, null=True, default="text_10")
    text_11 = RichTextField(blank=True, null=True, default="text_11")
    text_12 = RichTextField(blank=True, null=True, default="text_12")
    text_13 = RichTextField(blank=True, null=True, default="text_13")
    text_14 = RichTextField(blank=True, null=True, default="text_14")
    text_15 = RichTextField(blank=True, null=True, default="text_15")
    text_16 = RichTextField(blank=True, null=True, default="text_16")
    text_17 = RichTextField(blank=True, null=True, default="text_17")
    text_18 = RichTextField(blank=True, null=True, default="text_18")
    text_19 = RichTextField(blank=True, null=True, default="text_19")
    text_20 = RichTextField(blank=True, null=True, default="text_20")
    text_21 = RichTextField(blank=True, null=True, default="text_21")
    text_22 = RichTextField(blank=True, null=True, default="text_22")
    text_23 = RichTextField(blank=True, null=True, default="text_23")
    text_24 = RichTextField(blank=True, null=True, default="text_24")
    text_25 = RichTextField(blank=True, null=True, default="text_25")
    text_26 = RichTextField(blank=True, null=True, default="text_26")
    text_27 = RichTextField(blank=True, null=True, default="text_27")
    text_28 = RichTextField(blank=True, null=True, default="text_28")
    text_29 = RichTextField(blank=True, null=True, default="text_29")   


    char_1 = models.CharField(max_length=1000, blank=True, null=True, default="char_1")
    char_2 = models.CharField(max_length=1000, blank=True, null=True, default="char_2")
    char_3 = models.CharField(max_length=1000, blank=True, null=True, default="char_3")
    char_4 = models.CharField(max_length=1000, blank=True, null=True, default="char_4")
    char_5 = models.CharField(max_length=1000, blank=True, null=True, default="char_5")
    char_6 = models.CharField(max_length=1000, blank=True, null=True, default="char_6")
    char_7 = models.CharField(max_length=1000, blank=True, null=True, default="char_7")
    char_8 = models.CharField(max_length=1000, blank=True, null=True, default="char_8")
    char_9 = models.CharField(max_length=1000, blank=True, null=True, default="char_9")
    char_10 = models.CharField(max_length=1000, blank=True, null=True, default="char_10")
    char_11 = models.CharField(max_length=1000, blank=True, null=True, default="char_11")
    char_12 = models.CharField(max_length=1000, blank=True, null=True, default="char_12")
    char_13 = models.CharField(max_length=1000, blank=True, null=True, default="char_13")
    char_14 = models.CharField(max_length=1000, blank=True, null=True, default="char_14")
    char_15 = models.CharField(max_length=1000, blank=True, null=True, default="char_15")
    char_16 = models.CharField(max_length=1000, blank=True, null=True, default="char_16")
    char_17 = models.CharField(max_length=1000, blank=True, null=True, default="char_17")
    char_18 = models.CharField(max_length=1000, blank=True, null=True, default="char_18")
    char_19 = models.CharField(max_length=1000, blank=True, null=True, default="char_19")   
    char_20 = models.CharField(max_length=1000, blank=True, null=True, default="char_20")
    char_21 = models.CharField(max_length=1000, blank=True, null=True, default="char_21")
    char_22 = models.CharField(max_length=1000, blank=True, null=True, default="char_22")
    char_23 = models.CharField(max_length=1000, blank=True, null=True, default="char_23")
    char_24 = models.CharField(max_length=1000, blank=True, null=True, default="char_24")
    char_25 = models.CharField(max_length=1000, blank=True, null=True, default="char_25")
    char_26 = models.CharField(max_length=1000, blank=True, null=True, default="char_26")
    char_27 = models.CharField(max_length=1000, blank=True, null=True, default="char_27")
    char_28 = models.CharField(max_length=1000, blank=True, null=True, default="char_28")
    char_29 = models.CharField(max_length=1000, blank=True, null=True, default="char_29")   


    bool_1 = models.BooleanField(default=False)
    bool_2 = models.BooleanField(default=False)
    bool_3 = models.BooleanField(default=False)
    bool_4 = models.BooleanField(default=False)
    bool_5 = models.BooleanField(default=False)
    bool_6 = models.BooleanField(default=False)
    bool_7 = models.BooleanField(default=False)
    bool_8 = models.BooleanField(default=False)
    bool_9 = models.BooleanField(default=False)
    bool_10 = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.id

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    open_api_key = models.CharField(max_length=1000, blank=True, null=True)
    use_light_theme = models.BooleanField(default=False)
    def __str__(self):
        return self.user.email

